require "user.utils"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
-- require "user.tabnine"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
-- require "user.nvim-comment"
require "user.lightspeed"
require "user.gitsigns"
require "user.navic"
require "user.gitlinker"
--[[ require "user.nvim-tree" ]]
require "user.neotree"
require "user.bufferline"
require "user.lualine"
require "user.colorizer"
require "user.impatient"
require "user.indentline"
require "user.autocommands"
require "user.dap"
